# python script to create graphviz dot files to render the fonts

f = open("demofile2.txt", "w")


f.write("digraph g\n")
f.write("{\n")
f.write("layout=circo\n")
f.write("rankdir =TB;\n")
f.write("rank1 [style=invis];\n")
f.write("rank2 [style=invis];\n")
f.write("rank1 -> rank2 [color=invis];\n")
f.write("rank = same;\n")
f.write("\n")
f.write("\n")
f.write("0 [fillcolor = red style=filled]\n")
f.write("0 -> 1;\n")
f.write("1->2;\n")
f.write("2->3;\n")
f.write("3->4;\n")
f.write("4->5;\n")
f.write("5->6;\n")
f.write("6->7;\n")
f.write("7->8;\n")
f.write("8->9;\n")
f.write("9->10;\n")
f.write("10->11;\n")
f.write("11->12;\n")
f.write("12->13;\n")
f.write("13->14;\n")
f.write("14->15;\n")
f.write("15->16;\n")
f.write("16->17;\n")
f.write("17->18;\n")
f.write("18->19;\n")
f.write("19->20;\n")
f.write("20->21;\n")
f.write("21->22;\n")
f.write("22->23;\n")
f.write("23->0;\n")
f.write("rank2->6[style=invis];\n")
f.write("\n")
f.write("{rank=same; 2,rank2,5,12}\n")
f.write("{rank=max; 0}\n")
f.write("rankdir =TB;\n")
f.write("\n")
f.write("\n")
f.write("0 [fillcolor = red style=filled]\n")
f.write("\n")
f.write("\n")
f.write("}\n")

f.close()
